name: Go

on:
  push:
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o file-proxy .
    - name: see
      run: ls -a

    - name: Save Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: file-proxy
        path: file-proxy
    - name: see-again
      run: ls -a
  release:
    name: Create containerd Release
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    needs: [build]
    steps:
      - name: Download builds and release notes
        uses: actions/download-artifact@v2
      - name: see-again
        run: ls -a
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
          name: containerd ${{ needs.check.outputs.stringver }}
          draft: false
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
          body_path: ./readme.md
          files: |
             *
