name: Go

on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o file-proxy .
    - name: see
      run: ls -a

    - name: Save Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: file-proxy-file
        path: file-proxy
    - name: see-again
      run: ls -a
